### ISSUE TITLE
generateRnd not working ?

### ISSUE THREAD

**Issue by maxime1992** [adleroliveira/dreamjs#5]
Maybe i'm missing something. (probably)

In the command line i ran : `npm install --save dreamjs`  

When i follow this example : https://github.com/adleroliveira/dreamjs#generate-and-generaternd i only get empty objects.

Here's my code : 
```javascript
var dream = require('dreamjs');

dream.schema('User', {
  name: String
});

var data1 = dream
  .useSchema('User')
  .generate(3)
  .output();

var data2 = dream
  .useSchema('User')
  .generateRnd(3)
  .output();

console.log(data1); // [ { name: '' }, { name: '' }, { name: '' } ]
console.log(data2); // [ { name: '' }, { name: '' }, { name: '' } ]
```

I do not understand why names in data2 are empty.

Am i missing something ?

Thanks !

**Comment by handoing** [comment]
I also encountered the same problem.

**Comment by adleroliveira** [comment]
Hello,

It used to be a problem in a previous version. It got fixed so try updating your version.

In any case, there is a String custom type implemented, so try using 'string' instead of String. It should work.

**Comment by maxime1992** [comment]
```
npm install dreamjs  
npm update dreamjs  
npm list
```
![image](https://cloud.githubusercontent.com/assets/4950209/11626532/d3e070e6-9ce3-11e5-9339-bd410a11dcd8.png)

Problem is still the same.

**Comment by adleroliveira** [comment]
You were right. There was a bug.
I just published a fixed version. You can test it by pasting your code here:
https://tonicdev.com/npm/dreamjs

It is working now. Thanks

**Comment by maxime1992** [comment]
I updated to v0.1.3, and i had an error when running the demo.
I tried to remove the node_modules folder, i still have this error now : 
![image](https://cloud.githubusercontent.com/assets/4950209/11629759/5ab313e2-9cfa-11e5-9b41-ab51047a6f91.png)

**Comment by adleroliveira** [comment]
Version 0.1.14

![dreamjs_0_1_14](https://cloud.githubusercontent.com/assets/713256/11630185/03e4e0a0-9cdb-11e5-9d93-0d414da0361d.png)

**Comment by maxime1992** [comment]
Thanks it's working after updating again ! (V0.1.4)
![image](https://cloud.githubusercontent.com/assets/4950209/11630274/f07e2798-9cfc-11e5-944e-4c924be864a7.png)
